<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-7SBKKJ1" failures="3" tests="13" name="PSf_Static_Report_and_Call_Dispostion.PSF_Last_Attempt_Report" time="117.128" errors="0" timestamp="2024-12-05T14:26:19 IST" skipped="0">
  <testcase classname="PSf_Static_Report_and_Call_Dispostion.PSF_Last_Attempt_Report" name="Username" time="1.421"/>
  <system-out/>
  <testcase classname="PSf_Static_Report_and_Call_Dispostion.PSF_Last_Attempt_Report" name="Password" time="1.406"/>
  <system-out/>
  <testcase classname="PSf_Static_Report_and_Call_Dispostion.PSF_Last_Attempt_Report" name="Captcha" time="2.219"/>
  <system-out/>
  <testcase classname="PSf_Static_Report_and_Call_Dispostion.PSF_Last_Attempt_Report" name="SUBMIT_Button" time="2.190"/>
  <system-out/>
  <testcase classname="PSf_Static_Report_and_Call_Dispostion.PSF_Last_Attempt_Report" name="Click_On_PSF" time="41.266"/>
  <system-out/>
  <testcase classname="PSf_Static_Report_and_Call_Dispostion.PSF_Last_Attempt_Report" name="Remove_PouP" time="0.691"/>
  <system-out/>
  <testcase classname="PSf_Static_Report_and_Call_Dispostion.PSF_Last_Attempt_Report" name="Click_On_Static_Reports" time="1.088"/>
  <system-out/>
  <testcase classname="PSf_Static_Report_and_Call_Dispostion.PSF_Last_Attempt_Report" name="Click_On_Last_Attempt_Report" time="3.088"/>
  <system-out/>
  <testcase classname="PSf_Static_Report_and_Call_Dispostion.PSF_Last_Attempt_Report" name="Click_On_Generate" time="16.270"/>
  <system-out/>
  <testcase classname="PSf_Static_Report_and_Call_Dispostion.PSF_Last_Attempt_Report" name="Click_On_Workshop" time="3.603">
    <failure message="No Data Found for Workshop_Wise In Last_Attempt_Report : 0" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: No Data Found for Workshop_Wise In Last_Attempt_Report : 0
at org.testng.Assert.fail(Assert.java:99)
at PSf_Static_Report_and_Call_Dispostion.PSF_Last_Attempt_Report.Click_On_Workshop(PSF_Last_Attempt_Report.java:125)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- Click_On_Workshop -->
  <system-out/>
  <testcase classname="PSf_Static_Report_and_Call_Dispostion.PSF_Last_Attempt_Report" name="Click_On_Service_Type_Wise" time="21.847">
    <failure message="No Data Found for Service_Type_Wise In Last_Attempt_Report : 0" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: No Data Found for Service_Type_Wise In Last_Attempt_Report : 0
at org.testng.Assert.fail(Assert.java:99)
at PSf_Static_Report_and_Call_Dispostion.PSF_Last_Attempt_Report.Click_On_Service_Type_Wise(PSF_Last_Attempt_Report.java:259)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- Click_On_Service_Type_Wise -->
  <system-out/>
  <testcase classname="PSf_Static_Report_and_Call_Dispostion.PSF_Last_Attempt_Report" name="Click_On_DayWise" time="22.039">
    <failure message="No Data Found for Day Wise In Last_Attempt_Report : 0" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: No Data Found for Day Wise In Last_Attempt_Report : 0
at org.testng.Assert.fail(Assert.java:99)
at PSf_Static_Report_and_Call_Dispostion.PSF_Last_Attempt_Report.Click_On_DayWise(PSF_Last_Attempt_Report.java:192)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- Click_On_DayWise -->
  <system-out/>
  <testcase classname="PSf_Static_Report_and_Call_Dispostion.PSF_Last_Attempt_Report" name="Comparison_0f_all_Data" time="0.000"/>
  <system-out/>
</testsuite> <!-- PSf_Static_Report_and_Call_Dispostion.PSF_Last_Attempt_Report -->
